# Generated by Django 5.1.6 on 2025-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_delete_tactics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='eras',
        ),
        migrations.RemoveField(
            model_name='article',
            name='context',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='year',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='casualties',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='imageTactics',
        ),
        migrations.RemoveField(
            model_name='article',
            name='imageWar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tactics',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tactics_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='war',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(max_length=600),
        ),
        migrations.DeleteModel(
            name='Era',
        ),
        migrations.DeleteModel(
            name='War',
        ),
    ]
